#lang racket

(require "lexer.rkt")

(define lex-this (lambda (lexer input) (lambda () (lexer input))))
(define my-lexer (lex-this rktpython-lexer (open-input-string "+ - * / ** ( ) True not 12 13.24 hello _Hi")))
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
(my-lexer)
